# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import secdata_transfer_pb2 as secdata__transfer__pb2


class SecdataHandleStub(object):
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferKlineData = channel.unary_unary(
                '/secdata_transfer.SecdataHandle/TransferKlineData',
                request_serializer=secdata__transfer__pb2.KlineRequest.SerializeToString,
                response_deserializer=secdata__transfer__pb2.KlineReply.FromString,
                )


class SecdataHandleServicer(object):
    """
    """

    def TransferKlineData(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecdataHandleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferKlineData': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferKlineData,
                    request_deserializer=secdata__transfer__pb2.KlineRequest.FromString,
                    response_serializer=secdata__transfer__pb2.KlineReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secdata_transfer.SecdataHandle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecdataHandle(object):
    """
    """

    @staticmethod
    def TransferKlineData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secdata_transfer.SecdataHandle/TransferKlineData',
            secdata__transfer__pb2.KlineRequest.SerializeToString,
            secdata__transfer__pb2.KlineReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
